services:
  api:
    image: eduardokroetz/realtimechat
    ports:
        - "80:8080"
    depends_on: [db] 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: realtimechat-admin
      POSTGRES_PASSWORD: realtimechat-123
      POSTGRES_DB: realtimechat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/realtimechat/data

volumes:
  postgres_data: